module.exports = {
  // Auth
  AUTH_LOADING: "AUTH_LOADING",
  AUTH_END_LOADING: "AUTH_END_LOADING",
  AUTH_GET_DATA: "AUTH_GET_DATA",
  AUTH_CLEAR: "AUTH_CLEAR",

  // Profile
  PROFILE_LOADING: "PROFILE_LOADING",
  PROFILE_END_LOADING: "PROFILE_END_LOADING",
  PROFILE_GET_DATA: "PROFILE_GET_DATA",
  PROFILE_CLEAR: "PROFILE_CLEAR",

  // Site
  SITE_LOADING: "SITE_LOADING",
  SITE_END_LOADING: "SITE_END_LOADING",
  SITE_GET_DATA: "SITE_GET_DATA",
  SITE_CLEAR: "SITE_CLEAR",

  // Error
  GET_ERRORS: "GET_ERRORS",
  CLEAR_ERRORS: "CLEAR_ERRORS",
};
